### ISSUE TITLE
Consolidate common rust ci flows into reusable workflows

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/github-actions#1]
> Rather than copying and pasting from one workflow to another, you can make workflows reusable. You and anyone with access to the reusable workflow can then call the reusable workflow from another workflow.

Most of the CI across our repos has a lot of duplication & copy-paste. Consolidate any common steps used in our Rust workflows into a set of modularized reusable workflows based on this repo.

The following tasks are examples of what could be extracted into a set of common standardized CI workflows:
(see [fuel-core ci](https://github.com/FuelLabs/fuel-core/blob/master/.github/workflows/ci.yml) for reference)
 - linting Cargo.toml files
 - cargo verifications matrix (e.g build, test, lint, clippy, etc)
 - publishing crates
 - building and publishing docker images
 - building and publishing binaries (linux / mac executables)
 - CD workflows (e.g. preview environments)

**Comment by ellioty** [comment]
@Voxelot we discussed this earlier, but it seems like Cargo Verification, Publishing Binaries, CD Workflows (I think this is only used in fuel-core at the moment) are unique across repos at the moment, would it make sense to break this up into another tasks?
